name: Android Build & Release

on:
  push:
    branches:
      - '**'  # all branches
  workflow_dispatch:

permissions:
  contents: write   # Required for GitHub Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug

      - name: Upload Release APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.1.0          # ✅ Predefined tag
          name: "Release JNV BROWSER v1.1.0"
          body: |
            🔥 Automatic Releas
          files: |
            app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}